#!/bin/bash

if [ "$1" == uninstall ]; then
    echo 'Desinstalando BadVPN'
    rm -f /bin/badvpn
    rm -f /bin/badvpn-udpgw
    echo 'Desinstalação completa'
fi

if [ "$1" == start ]; then
    if [ ! -f "/bin/badvpn-udpgw" ]; then
        echo "Baixando BadVPN"
        wget -O /bin/badvpn-udpgw64 https://raw.githubusercontent.com/TelksBr/badvpn/master/badvpn-udpgw64 &>/dev/null
        chmod +x /bin/badvpn-udpgw64
    fi

    /bin/badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 1000 --max-connections-for-client 1000 --client-socket-sndbuf 0 --udp-mtu 9000 &
    echo 'Badvpn iniciando no endereço 127.0.0.1:7200'
fi

if [ "$1" == stop ]; then
    badvpnpid="$(ps x | grep badvpn-udpgw | grep -v grep | awk '{print $1}')"
    if [ -n "$badvpnpid" ]; then
        kill -9 "$badvpnpid" >/dev/null 2>/dev/null
        echo 'Badvpn parado'
    else
        echo 'Badvpn não está em execução'
    fi
fi

if [ "$1" == "uninstall" ] || [ "$1" == "start" ] || [ "$1" == "stop" ]; then
    exit
fi

# Configurar o serviço systemd
cat <<EOF > /etc/systemd/system/badvpn.service
[Unit]
Description=BadVPN UDP Gateway
After=network.target

[Service]
ExecStart=/bin/badvpn-udpgw --listen-addr 127.0.0.1:7200 --max-clients 1000 --max-connections-for-client 1000 --client-socket-sndbuf 0 --udp-mtu 9000
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable badvpn.service
systemctl start badvpn.service

echo "Serviço systemd do BadVPN instalado e iniciado com sucesso."
