#!/bin/bash

# Verifica se o script está sendo executado com privilégios de root
if [[ $EUID -ne 0 ]]; then
   echo "Este script deve ser executado como root" 
   exit 1
fi

# Função para instalar o serviço systemd
install_systemd_service() {
    cat <<EOF > /etc/systemd/system/badvpn.service
[Unit]
Description=BadVPN UDP Gateway

[Service]
ExecStart=/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 1000 --client-socket-sndbuf 0 --udp-mtu 9000
Restart=always

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable badvpn.service
    systemctl start badvpn.service

    echo "Serviço systemd do BadVPN instalado e iniciado com sucesso."
}

if [ "$1" == "uninstall" ]; then
    echo "Desinstalando BadVPN"
    systemctl stop badvpn.service
    systemctl disable badvpn.service
    rm -f /etc/systemd/system/badvpn.service
    systemctl daemon-reload
    echo "Desinstalação completa"
elif [ "$1" == "start" ]; then
    install_systemd_service
    echo "Badvpn iniciando no endereço 127.0.0.1:7300"
elif [ "$1" == "stop" ]; then
    echo "Parando BadVPN"
    systemctl stop badvpn.service
    systemctl disable badvpn.service
    rm -f /etc/systemd/system/badvpn.service
    systemctl daemon-reload
    echo "BadVPN parado e desinstalado"
else
    echo "Uso: $0 [start|stop|uninstall]"
fi
